apiVersion: apps/v1
kind: Deployment
metadata:
  # base와 동일하게 명시해서 patch시 어떤 deployment에 대한 수정인지 kustomize가 인식
  name: app
spec:
  template:
    spec:
      containers:
        - name: microservice
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            # 서비스 준비상태에 대한 초기 확인 지연 시간 지정
            # TODO : 배포 후에 적정한 값으로 수정
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            # 서비스 준비상태에 대한 초기 확인 지연 시간 지정
            # TODO : 배포 후에 적정한 값으로 수정
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          ports:
            - containerPort: 8080
            - $patch: replace # 어레이 전체를 이것으로 바꿈.