apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: microservice
          resources:
            requests:
              memory: 128Mi
              cpu: 0.5       
            limits:
              # TODO : OutOfMemory가 발생되지 않도록 값 수정
              memory: 256Mi
              cpu: 1